In [1]:
tinggi = [180, 215, 210, 210, 188, 176, 209, 200] # dalam cm 

# Import numpy dengan alias np
import numpy as np

# Buat numpy array dengan list tinggi beri nama variabel np_tinggi
np_tinggi = np.array(tinggi)


# Print tipe data np_baseball
print('Tipe data dari np_tinggi :',type(np_tinggi))

Tipe data dari np_tinggi : <class 'numpy.ndarray'>


In [2]:
# Buat np_tinggi menjadi dalam satuan meter
np_tinggi = np_tinggi/100

# print np_tinggi
print(np_tinggi)

[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


In [3]:
berat = [88.5, 100, 98, 101, 78.3, 65.3, 109, 110]

# Buatlah numpy array dari list berat dan simpan dalam np_berat
np_berat = np.array(berat)

# hitung bmi dari berat dan tinggi simpan ke dalam variabel bmi
bmi = np_berat / np_tinggi ** 2

print(bmi)

[27.31481481 21.63331531 22.22222222 22.90249433 22.15368945 21.08083678
 24.95364117 27.5       ]


In [4]:
# Coba jawabanmu disini
np.array([4, 3, 0]) + np.array([0, 2, 2]) #B

array([4, 5, 2])

In [5]:
# print hasil np_berat yang melik index terakhir
print(np_berat[-1])

# print 5 elemen terakhir dari np_tingg
print(np_tinggi[-5:])

110.0
[2.1  1.88 1.76 2.09 2.  ]


In [6]:
pemain_basket = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

# Buatlah 2D array dari pemain_basket simpan dalam variabel basket_2d
basket_2d = np.array([[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]])

# print tipe dari basket_2d
print('Tipe dari basket_2d : ', type(basket_2d))

# print basket_2d
print(basket_2d)

# print dimensi dari basket_2d dengan basket_2d.shape
print(basket_2d.shape)

Tipe dari basket_2d :  <class 'numpy.ndarray'>
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
(4, 2)


In [7]:
# Gunakan slicing untuk untuk mengambil hanya kolom pertama dari basket_2d
basket_2d[0]
print(basket_2d)

# Gunakan slicing untuk mendapatkan 2 baris terakhir dan hanya kolom kedua dari basket_2d
basket_2d[-2, 1:]

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


array([98.5])

In [8]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [9]:
# Print dengan tambahkan berat dari basket_2d (kolom kedua) dengan 5 
#array_2d[baris, kolom]

print(basket_2d[:, 1] + 5)

# Print dengan mengubah tinggi basket_2d (kolom pertama) yang awalnya satuannya cm menjadi m
print(basket_2d[:, 0]/100)

[ 83.4 107.7 103.5  80.2]
[1.8  2.15 2.1  1.88]


In [10]:
# Berapakah mean dari np_tinggi? Kemudian print
print('Mean pada tinggi :', np.mean(np_tinggi))


# Berapakah median dari np_tinggi? Kemudian print
print('Median pada tinggi :', np.median(np_tinggi))

Mean pada tinggi : 1.9849999999999999
Median pada tinggi : 2.045


In [11]:
# Print tinggi dari basket_2d (kolom pertama)
rata_rata = np.mean(basket_2d[:, 0])
print("Rata - Rata: " + str(rata_rata))

# Print median dari tinggi basket_2d
med = np.median(basket_2d)
print("Median: " + str(med))

# Print standar deviasi dari basket_2d
stddev = np.std(basket_2d)
print("Standard Deviation: " + str(stddev))

# Print korelasi antara kolom pertama dengan kedua dari basket_2d
korelasi = np.corrcoef(basket_2d)

Rata - Rata: 198.25
Median: 141.35
Standard Deviation: 56.390973346804365
